(function(g){
function Player(video,state){this.video=video;this.state=state;this.timer=null;this.trace=[];this.attempt=0;this.hls=null;this.ts=null;this.resolver=new StreamResolver({endpoint:(state.settings&&state.settings.backend)||''});this.telemetryEndpoint=(this.resolver.endpoint||'https://iptvwebos.onrender.com').replace(/\/$/,'')+'/telemetry';this.current=null}
Player.prototype.report=function(event,ch,url){try{var x=new XMLHttpRequest();x.open('POST',this.telemetryEndpoint,true);x.setRequestHeader('Content-Type','application/json');x.send(JSON.stringify({event:event,channel:(ch&&ch.name)||'',url:url||(ch&&ch.url)||'',mse:!!g.MediaSource,hls:!!g.Hls,hlsSupported:!!(g.Hls&&g.Hls.isSupported&&g.Hls.isSupported()),mpegts:!!g.mpegts,mpegtsSupported:!!(g.mpegts&&g.mpegts.isSupported&&g.mpegts.isSupported()),userAgent:navigator.userAgent}))}catch(e){}};
Player.prototype.log=function(s){this.trace.push(s);if(this.trace.length>8)this.trace.shift();this.onState(this.trace.join(' > '));this.report(s,this.current,this.current&&this.current.url)};
Player.prototype.mediaError=function(){var e=this.video.error;if(!e)return'unknown';return'code '+e.code+(e.message?' '+e.message:'')};
Player.prototype.play=function(ch){this.stop();this.current=ch;this.trace=[];this.attempt++;var self=this,a=this.attempt;this.report('PLAY pressed',ch,ch.url);this.log('PROBE opening');this.resolver.resolve(ch,function(err,r){if(a!==self.attempt)return;if(err){self.log('PROBE fail '+err.message);return self.tryBackendOrNative(ch,ch.url,a)}var kind=(r&&r.kind)||'unknown',url=(r&&r.url)||ch.url;self.log('PROBE '+kind);if(kind==='hls')return self.tryMse(ch,url,a,false);if(kind==='ts'||kind==='mpegts'||kind==='mpeg-ts')return self.tryMpegTs(ch,url,a);self.tryBackendOrNative(ch,url,a)})};
Player.prototype.tryMpegTs=function(ch,url,attempt){var self=this,v=this.video,start=Date.now();if(attempt!==this.attempt)return;clearTimeout(this.timer);if(!g.MediaSource||!g.mpegts||!g.mpegts.isSupported||!g.mpegts.isSupported()){this.log('MPEGTS.JS unsupported');return this.tryBackendOrNative(ch,url,attempt)}this.log('MPEGTS opening');try{var p=g.mpegts.createPlayer({type:'mpegts',isLive:true,url:url},{enableWorker:false,enableStashBuffer:true,stashInitialSize:384*1024,liveBufferLatencyChasing:true,liveBufferLatencyMaxLatency:3,liveBufferLatencyMinRemain:1});this.ts=p;p.attachMediaElement(v);p.on(g.mpegts.Events.ERROR,function(type,detail,info){if(attempt!==self.attempt)return;self.log('MPEGTS ERROR '+(detail||type||'unknown'));try{p.destroy()}catch(e){}if(self.ts===p)self.ts=null;self.tryBackendOrNative(ch,url,attempt)});v.onplaying=function(){if(attempt===self.attempt)self.log('MPEGTS PLAY '+(Date.now()-start)+'ms')};p.load();var q=p.play();if(q&&q.catch)q.catch(function(e){if(attempt===self.attempt)self.log('MPEGTS play() '+(e&&e.name||'reject'))});this.timer=setTimeout(function(){if(attempt!==self.attempt)return;self.log('MPEGTS timeout');try{p.destroy()}catch(e){}if(self.ts===p)self.ts=null;self.tryBackendOrNative(ch,url,attempt)},30000)}catch(e){this.log('MPEGTS exception '+e.message);this.tryBackendOrNative(ch,url,attempt)}};
Player.prototype.tryMse=function(ch,url,attempt,isFallback){var self=this,v=this.video,start=Date.now();if(attempt!==this.attempt)return;if(!g.MediaSource){this.log('MSE unavailable');return this.tryNative(ch,url,attempt)}if(!g.Hls||!g.Hls.isSupported||!g.Hls.isSupported()){this.log('HLS.JS unsupported');return this.tryNative(ch,url,attempt)}this.log((isFallback?'MSE FALLBACK':'MSE')+' opening');try{this.hls=new g.Hls({enableWorker:false,lowLatencyMode:false,backBufferLength:30,maxBufferLength:20,maxMaxBufferLength:40,manifestLoadingTimeOut:15000,levelLoadingTimeOut:15000,fragLoadingTimeOut:20000});var h=this.hls;h.on(g.Hls.Events.MEDIA_ATTACHED,function(){if(attempt!==self.attempt)return;self.log('MSE attached');h.loadSource(url)});h.on(g.Hls.Events.MANIFEST_PARSED,function(ev,data){if(attempt!==self.attempt)return;self.log('MSE manifest '+((data&&data.levels&&data.levels.length)||0)+' levels');var q=v.play();if(q&&q.catch)q.catch(function(e){self.log('MSE play() '+(e&&e.name||'reject'))})});h.on(g.Hls.Events.ERROR,function(ev,data){if(attempt!==self.attempt)return;self.log('MSE '+(data&&data.type||'error')+' '+(data&&data.details||''));if(data&&data.fatal){try{h.destroy()}catch(e){}self.hls=null;if(!isFallback&&self.resolver.endpoint)return self.tryBackend(ch,attempt);self.tryNative(ch,url,attempt)}});v.onplaying=function(){if(attempt===self.attempt)self.log('MSE PLAY '+(Date.now()-start)+'ms')};h.attachMedia(v);this.timer=setTimeout(function(){if(attempt!==self.attempt)return;self.log('MSE timeout');try{h.destroy()}catch(e){}self.hls=null;if(!isFallback&&self.resolver.endpoint)self.tryBackend(ch,attempt);else self.tryNative(ch,url,attempt)},30000)}catch(e){this.log('MSE exception '+e.message);this.tryNative(ch,url,attempt)}};
Player.prototype.tryBackendOrNative=function(ch,url,attempt){if(this.resolver.endpoint)return this.tryBackend(ch,attempt);this.tryNative(ch,url,attempt)};
Player.prototype.tryBackend=function(ch,attempt){var u=this.resolver.fallbackUrl(ch,'transcode');if(!u)return this.tryNative(ch,ch.url,attempt);this.log('BACKEND HLS');this.tryMse(ch,u,attempt,true)};
Player.prototype.tryNative=function(ch,url,attempt){var self=this,v=this.video,start=Date.now();if(attempt!==this.attempt)return;clearTimeout(this.timer);this.log('NATIVE opening');try{v.onplaying=function(){if(attempt===self.attempt)self.log('NATIVE PLAY '+(Date.now()-start)+'ms')};v.onerror=function(){if(attempt===self.attempt)self.log('NATIVE FAIL '+self.mediaError())};v.src=url;var q=v.play();if(q&&q.catch)q.catch(function(e){if(attempt===self.attempt)self.log('NATIVE play() '+(e&&e.name||'reject'))})}catch(e){this.log('NATIVE exception '+e.message)}};
Player.prototype.stop=function(){this.attempt++;clearTimeout(this.timer);if(this.hls){try{this.hls.destroy()}catch(e){}this.hls=null}if(this.ts){try{this.ts.pause();this.ts.unload();this.ts.detachMediaElement();this.ts.destroy()}catch(e){}this.ts=null}try{this.video.onplaying=null;this.video.onerror=null;this.video.pause();this.video.removeAttribute('src');this.video.load()}catch(e){}};
Player.prototype.onState=function(t){var el=document.getElementById('playState');if(el)el.textContent=t};
g.IPTVPlayer=Player;
})(window);
