'use strict';
var express=require('express'),http=require('http'),https=require('https'),URL=require('url').URL,cp=require('child_process'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
var app=express(),PORT=process.env.PORT||8787,MAX_REDIRECT=5,HLS_ROOT=path.join(os.tmpdir(),'iptvwebos-hls'),sessions={};fs.mkdirSync(HLS_ROOT,{recursive:true});
app.use(function(req,res,next){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Range,Content-Type');if(req.method==='OPTIONS')return res.status(204).end();next()});app.use(express.json({limit:'16kb'}));
app.post('/telemetry',function(req,res){var b=req.body||{},url=String(b.url||'');try{if(url){var u=new URL(url);url=u.protocol+'//'+u.host+u.pathname}}catch(e){url='invalid'}console.log('PLAYER_TELEMETRY '+JSON.stringify({event:String(b.event||'').slice(0,160),channel:String(b.channel||'').slice(0,120),url:url.slice(0,300),mse:!!b.mse,hls:!!b.hls,hlsSupported:!!b.hlsSupported,userAgent:String(b.userAgent||'').slice(0,240),ts:Date.now()}));res.status(204).end()});
function valid(raw){try{var u=new URL(raw);return u.protocol==='http:'||u.protocol==='https:'}catch(e){return false}}
function head(raw,n,cb){var finished=false;function finish(e,x){if(finished)return;finished=true;cb(e,x)}if(n>MAX_REDIRECT)return finish(Error('too many redirects'));var u=new URL(raw),lib=u.protocol==='https:'?https:http,r=lib.request(u,{method:'GET',headers:{'User-Agent':'Mozilla/5.0 (webOS.TV; LGTV)','Accept':'*/*','Range':'bytes=0-4095'}},function(x){if(x.statusCode>=300&&x.statusCode<400&&x.headers.location){x.resume();return head(new URL(x.headers.location,u).toString(),n+1,finish)}var chunks=[],size=0;x.on('data',function(d){if(size<4096){chunks.push(d);size+=d.length}if(size>=4096)x.destroy()});x.on('close',function(){finish(null,{url:u.toString(),status:x.statusCode,type:x.headers['content-type']||'',body:Buffer.concat(chunks).toString('utf8')})});x.on('end',function(){finish(null,{url:raw,status:x.statusCode,type:x.headers['content-type']||'',body:Buffer.concat(chunks).toString('utf8')})})});r.setTimeout(6000,function(){r.destroy(Error('timeout'))});r.on('error',finish);r.end()}
function kind(x){var t=(x.type||'').toLowerCase(),b=x.body||'',u=(x.url||'').toLowerCase().split('?')[0];if(t.indexOf('mpegurl')>=0||b.indexOf('#EXTM3U')===0||/\.m3u8$/.test(u))return'hls';if(t.indexOf('dash')>=0||b.indexOf('<MPD')>=0||/\.mpd$/.test(u))return'dash';if(t.indexOf('mp2t')>=0||/\.ts$/.test(u))return'ts';return'unknown'}
function checkFfmpeg(cb){var bin=process.env.FFMPEG_PATH||'ffmpeg';cp.execFile(bin,['-version'],{timeout:3000},function(e,stdout){if(e)return cb(false,null,e.message);cb(true,String(stdout||'').split(/\r?\n/)[0]||null,null)})}
app.get('/health',function(req,res){checkFfmpeg(function(ok,version,error){res.status(ok?200:503).json({ok:ok,ffmpeg:ok,ffmpegVersion:version,error:error})})});
function privateHost(host){host=String(host||'').toLowerCase();if(host==='localhost'||host.endsWith('.localhost')||host==='metadata.google.internal')return true;var m=host.match(/^\d+\.\d+\.\d+\.\d+$/);if(m){var p=host.split('.').map(Number),a=p[0],b=p[1];return a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a===0}if(host.indexOf(':')>=0)return host==='::1'||host.indexOf('fc')===0||host.indexOf('fd')===0||host.indexOf('fe80:')===0;return false}
function safe(raw){if(!valid(raw))return false;try{return !privateHost(new URL(raw).hostname)}catch(e){return false}}
function removeDir(dir){try{fs.rmSync(dir,{recursive:true,force:true})}catch(e){}}
function startHls(raw,transcode,req,res){var id=crypto.randomBytes(12).toString('hex'),dir=path.join(HLS_ROOT,id);fs.mkdirSync(dir,{recursive:true});var playlist=path.join(dir,'index.m3u8'),segment=path.join(dir,'seg%05d.ts'),bin=process.env.FFMPEG_PATH||'ffmpeg';var args=['-hide_banner','-loglevel','warning','-fflags','+genpts+discardcorrupt','-err_detect','ignore_err','-analyzeduration','10000000','-probesize','10000000','-user_agent','Mozilla/5.0 (webOS.TV; LGTV)','-i',raw,'-map','0:v:0?','-map','0:a:0?','-sn','-dn'];if(transcode){args=args.concat(['-vf','setpts=N/(30*TB),fps=30,format=yuv420p','-af','aresample=async=1:first_pts=0,asetpts=N/SR/TB','-c:v','libx264','-preset','veryfast','-tune','zerolatency','-profile:v','main','-level:v','4.0','-pix_fmt','yuv420p','-g','60','-keyint_min','60','-sc_threshold','0','-force_key_frames','expr:gte(t,n_forced*2)','-c:a','aac','-ac','2','-ar','48000','-b:a','128k'])}else args=args.concat(['-c','copy','-avoid_negative_ts','make_zero']);args=args.concat(['-max_interleave_delta','0','-muxdelay','0','-muxpreload','0','-f','hls','-hls_time','2','-hls_list_size','6','-hls_flags','delete_segments+omit_endlist+independent_segments+program_date_time','-hls_segment_type','mpegts','-hls_segment_filename',segment,playlist]);var p=cp.spawn(bin,args,{stdio:['ignore','ignore','pipe']});sessions[id]={process:p,dir:dir,last:Date.now()};p.stderr.on('data',function(d){console.log('FFMPEG_HLS '+id+' '+String(d).trim())});p.on('close',function(code){console.log('FFMPEG_HLS_CLOSE '+id+' '+code);if(sessions[id])sessions[id].process=null});p.on('error',function(e){console.error('FFMPEG_HLS_ERROR '+id+' '+e.message)});var tries=0,t=setInterval(function(){tries++;if(fs.existsSync(playlist)){try{var text=fs.readFileSync(playlist,'utf8'),m=text.match(/^(seg\d+\.ts)$/m);if(m&&fs.existsSync(path.join(dir,m[1]))&&fs.statSync(path.join(dir,m[1])).size>188*10){clearInterval(t);return res.redirect(302,'/hls/'+id+'/index.m3u8')}}catch(e){}}if(tries>=400){clearInterval(t);try{p.kill('SIGTERM')}catch(e){};removeDir(dir);delete sessions[id];if(!res.headersSent)res.status(502).json({error:'HLS startup timeout'})}},100)}
app.get('/resolve',function(req,res){var raw=req.query.url;if(!safe(raw))return res.status(400).json({error:'invalid or blocked URL'});head(raw,0,function(e,info){if(e)return res.status(502).json({error:e.message});res.json({url:info.url,kind:kind(info),mode:'probe',status:info.status,type:info.type})})});app.get('/remux',function(req,res){var raw=req.query.url;if(!safe(raw))return res.status(400).json({error:'invalid or blocked URL'});startHls(raw,false,req,res)});app.get('/transcode',function(req,res){var raw=req.query.url;if(!safe(raw))return res.status(400).json({error:'invalid or blocked URL'});startHls(raw,true,req,res)});app.get('/hls/:id/:file',function(req,res){var s=sessions[req.params.id];if(!s)return res.status(404).end();s.last=Date.now();var name=req.params.file;if(!/^index\.m3u8$|^seg\d+\.ts$/.test(name))return res.status(400).end();var f=path.join(s.dir,name);if(!fs.existsSync(f))return res.status(404).end();if(name.endsWith('.m3u8'))res.type('application/vnd.apple.mpegurl');else res.type('video/mp2t');res.setHeader('Cache-Control','no-store');res.sendFile(f)});setInterval(function(){var now=Date.now();Object.keys(sessions).forEach(function(id){var s=sessions[id];if(now-s.last>120000){try{if(s.process&&!s.process.killed)s.process.kill('SIGTERM')}catch(e){};removeDir(s.dir);delete sessions[id]}})},30000).unref();app.listen(PORT,function(){console.log('IPTV fallback backend listening on '+PORT);checkFfmpeg(function(ok,version,err){console.log('STARTUP_FFMPEG '+JSON.stringify({ok:ok,version:version,error:err||null}))})});